In [21]:
import numpy as np
import pandas as pd

In [281]:
# Load all sample data
clients_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/clients.csv')
office_expenses_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/office_expenses.csv')
home_listings_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/home_listings.csv')
transactions_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/transactions.csv')
employees_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/employees.csv')

In [289]:
clients_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/clients.csv')

clients_df

,Name,Email,Phone Number,Street,State,Zip Code,Client Type,Preferred Home Type,Preferred Number of Bedrooms,Preferred Number of Bathrooms,Preferred Square Footage,Preferred School Rating,Assigned Employee
0,"Melton, Ashley",ashley.melton@example.com,6076274707,549 Nguyen Underpass Suite 698,NY,13309,buyer,condo,5.0,3.0,2775.0,5.0,"Tanner, Sean"
1,"Cooley, Melissa",melissa.cooley@example.com,292-810-9738,44362 Dennis Hill,CT,6205,buyer,single house,1.0,1.0,1812.0,6.0,"Mcguire, Jeanette"
2,"Gibbs, Angela",angela.gibbs@example.com,001-766-553-7400,9515 Joseph Manor Apt. 900,NY,10370,owner,NaN,NaN,NaN,NaN,NaN,"Davis, Ashley"
3,"Gardner, Jasmine",jasmine.gardner@example.com,535.355.1974x252,273 Bernard Ports Apt. 062,NJ,8790,renter,condo,5.0,2.0,2498.0,2.0,"Rios, Mary"
4,"Castro, Charles",charles.castro@example.com,511.384.1001x42377,45976 Stone Squares Apt. 678,NY,14496,owner,NaN,NaN,NaN,NaN,NaN,"Rios, Mary"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"Horton, Martin",martin.horton@example.com,489-865-0219x64890,89051 Linda Flat Suite 220,CT,6349,seller,NaN,NaN,NaN,NaN,NaN,"Taylor, Jessica"
996,"Rich, David",david.rich@example.com,817-797-4913,8448 April Circles Apt. 912,CT,6385,buyer,townhouse,4.0,3.0,2622.0,6.0,"Barnes, Michael"
997,"Vega, Robert",robert.vega@example.com,(958)510-7518x6761,9070 Paula Land,NJ,7704,buyer,apartment,4.0,2.0,2119.0,9.0,"Clements, Derek"
998,"Jimenez, Maria",maria.jimenez@example.com,899-394-4893,069 Johnson Plaza,CT,6019,seller,NaN,NaN,NaN,NaN,NaN,"Leon, Patrick"
999,"Miller, Brandon",brandon.miller@example.com,+1-345-259-2125x79362,411 Robert Ford,NJ,8336,seller,NaN,NaN,NaN,NaN,NaN,"Taylor, Jessica"

In [290]:
office_expenses_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/office_expenses.csv')
office_expenses_df

,Office Name,Address,State,City,Date,Expense Type,Amount
0,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,rent,11641
1,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,water,167
2,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,electric,261
3,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,internet,159
4,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-03-28,rent,11641
...,...,...,...,...,...,...,...
2799,Dream Homes Buffalo,40298 Perez Drive Suite 835,NY,Buffalo,2024-02-22,internet,119
2800,Dream Homes Buffalo,40298 Perez Drive Suite 835,NY,Buffalo,2024-03-23,rent,21922
2801,Dream Homes Buffalo,40298 Perez Drive Suite 835,NY,Buffalo,2024-03-23,water,205
2802,Dream Homes Buffalo,40298 Perez Drive Suite 835,NY,Buffalo,2024-03-23,electric,356
2803,Dream Homes Buffalo,40298 Perez Drive Suite 835,NY,Buffalo,2024-03-23,internet,129

In [291]:
home_listings_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/home_listings.csv')
home_listings_df

,Listing ID,Title,Description,Home Type,Bedrooms,Bathrooms,Year Built,Square Footage,Listed Price,Listing Type,Amenities,Street,City,Zip Code,Commute Options,Listing Date,Nearby Schools,Utilities,Owner/Seller Name
0,8585561689,Charming 4-Bedroom Townhouse with parking,This charming 4-bedroom townhouse offers a spa...,Townhouse,4,2,1985,2446,4125,Rent,"['parking', 'patio', 'fireplace', 'doorman', '...",56162 Omar Park,New York,10060,"['Bus 103', 'Bus 101']",2021-05-05,"[{'name': 'Jackson, Smith and Williams', 'rati...",['Verizon'],"Wiggins, Michael"
1,1550678141,Luxurious 3-Bedroom Townhouse with parking,This luxurious 3-bedroom townhouse offers a sp...,Townhouse,3,2,1921,1853,923862,Sale,"['pool', 'gym', 'fireplace', 'patio', 'parking']",466 Dawson Terrace Apt. 858,New York,11033,"['Train A', 'Train B', 'Bus 101']",2022-01-24,"[{'name': 'Wilson Inc', 'rating': 8}, {'name':...","['Optimum', 'Spectrum']","Chavez, Lisa"
2,8476052241,Charming 1-Bedroom Apartment with pool,This charming 1-bedroom apartment offers a spa...,Apartment,1,3,1902,3077,4310,Rent,"['patio', 'gym', 'parking', 'pool', 'doorman']",9026 Chad Valley,Buffalo,10410,['Bus 101'],2021-07-17,"[{'name': 'Weaver-Vargas', 'rating': 0}, {'nam...",['Optimum'],"Bruce, Chris"
3,2107612233,Charming 3-Bedroom Townhouse with parking,This charming 3-bedroom townhouse offers a spa...,Townhouse,3,2,2011,2079,2664,Rent,"['patio', 'gym', 'parking']",827 Santos Stream,Elizabeth,7725,"['Bus 102', 'Train B', 'Bus 103']",2023-09-10,"[{'name': 'Baker-Potter', 'rating': 8}, {'name...","['Spectrum', 'Con Edison', 'National Grid']","Sandoval, Victoria"
4,4929040086,Luxurious 3-Bedroom Condo with pool,This luxurious 3-bedroom condo offers a spacio...,Condo,3,1,1929,1712,781721,Sale,"['patio', 'fireplace', 'pool', 'parking']",3635 Alison Bridge,Stamford,6119,['Train B'],2024-02-15,"[{'name': 'Fletcher, Poole and Alvarez', 'rati...",['Verizon'],"Bryant, Kaitlyn"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,7919467850,Luxurious 5-Bedroom Townhouse with doorman,This luxurious 5-bedroom townhouse offers a sp...,Townhouse,5,1,1977,908,1231441,Sale,"['doorman', 'parking', 'pool', 'fireplace']",28291 Brandon Stravenue,Syracuse,13271,['Bus 103'],2022-05-26,"[{'name': 'Montgomery-Waters', 'rating': 3}]","['Verizon', 'Optimum']","Oliver, Matthew"
996,9775018591,Charming 3-Bedroom Townhouse with patio,This charming 3-bedroom townhouse offers a spa...,Townhouse,3,2,2014,1019,3652,Rent,"['doorman', 'patio']",13328 Waters Ford Suite 061,New York,12965,"['Train A', 'Bus 102']",2021-12-20,"[{'name': 'Knapp, Jacobson and Valdez', 'ratin...","['Con Edison', 'National Grid', 'Verizon']","Scott, Erica"
997,6429659679,Luxurious 1-Bedroom Single Family Home with gym,This luxurious 1-bedroom single family home of...,Single Family Home,1,2,1914,2821,488191,Sale,"['gym', 'parking', 'pool']",033 Wilson Isle Suite 690,Buffalo,11266,['Train A'],2022-10-08,"[{'name': 'Rodriguez LLC', 'rating': 1}, {'nam...",['Spectrum'],"Combs, Mary"
998,1858711056,Charming 3-Bedroom Townhouse with parking,This charming 3-bedroom townhouse offers a spa...,Townhouse,3,2,1965,1167,4081,Rent,"['patio', 'parking', 'gym', 'pool', 'fireplace']",7457 Paula Pines,New Haven,6077,"['Bus 103', 'Train C']",2023-01-11,"[{'name': 'Maldonado, Smith and Fernandez', 'r...","['Optimum', 'National Grid']","Rojas, Kim"
999,1828375380,Charming 4-Bedroom Apartment with doorman,This charming 4-bedroom apartment offers a spa...,Apartment,4,1,2008,553,2836,Rent,"['patio', 'fireplace', 'pool', 'doorman']",92007 Michael Corner Apt. 146,New Haven,6056,['Bus 103'],2023-04-13,"[{'name': 'Smith-Good', 'rating': 8}, {'name':...","['National Grid', 'Optimum', 'PSE&G']","Martinez, Robert"

In [282]:
office_expenses_df.head()

,Office Name,Address,State,City,Date,Expense Type,Amount
0,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,rent,11641
1,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,water,167
2,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,electric,261
3,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-02-26,internet,159
4,Dream Homes Bridgeport,09080 Stone Hill,CT,Bridgeport,2023-03-28,rent,11641

In [295]:
import pandas as pd
import numpy as np
import random

# Extract address data ensuring all required columns are present
clients_addresses = clients_df[['Street', 'State']].copy()
clients_addresses['City'] = np.nan  # Add a City column filled with NaNs

office_expenses_addresses = office_expenses_df[['Address', 'State', 'City']].rename(columns={'Address': 'Street'})

home_listings_addresses = home_listings_df[['Street', 'City']].copy()
home_listings_addresses['State'] = np.nan  # Add a State column filled with NaNs

# Combine address data ensuring no rows are dropped due to missing information
combined_addresses = pd.concat([clients_addresses, office_expenses_addresses, home_listings_addresses], ignore_index=True)

# Remove duplicates
combined_addresses = combined_addresses.drop_duplicates()

# Function to separate street and unit based on the first comma or the first three words
def separate_street_and_unit(street):
    if ',' in street:
        parts = street.split(',', 1)
        return parts[0].strip(), parts[1].strip()
    parts = street.split()
    if len(parts) > 3:
        return ' '.join(parts[:3]), ' '.join(parts[3:])
    return street, ''

# Apply the function to extract and update Street and Unit
combined_addresses[['Street', 'Unit']] = combined_addresses['Street'].apply(lambda x: pd.Series(separate_street_and_unit(x)))

# Standardize and fill in missing values
combined_addresses['Country'] = 'USA'
combined_addresses['Zip_Code'] = combined_addresses['Zip_Code'].astype(str) if 'Zip_Code' in combined_addresses.columns else ''

# Preserve existing Zip Codes if available and generate random 5 digits for missing ones
combined_addresses['Zip_Code'] = combined_addresses['Zip_Code'].replace('', np.nan)
# Change here: Generate the random zip codes as a pandas Series instead of a numpy array
zip_codes_to_fill = pd.Series(np.random.randint(10000, 99999, size=len(combined_addresses))).astype(str)
combined_addresses['Zip_Code'].fillna(zip_codes_to_fill, inplace=True)

# Generating values for address_id
combined_addresses.insert(0, 'address_id', range(1, 1 + len(combined_addresses)))

print(combined_addresses)

      address_id                   Street State       City       Unit Country  \
0              1     549 Nguyen Underpass    NY        NaN  Suite 698     USA
1              2        44362 Dennis Hill    CT        NaN                USA
2              3        9515 Joseph Manor    NY        NaN   Apt. 900     USA
3              4        273 Bernard Ports    NJ        NaN   Apt. 062     USA
4              5      45976 Stone Squares    NY        NaN   Apt. 678     USA
...          ...                      ...   ...        ...        ...     ...
4799        2028  28291 Brandon Stravenue   NaN   Syracuse                USA
4800        2029        13328 Waters Ford   NaN   New York  Suite 061     USA
4801        2030          033 Wilson Isle   NaN    Buffalo  Suite 690     USA
4802        2031         7457 Paula Pines   NaN  New Haven                USA
4803        2032     92007 Michael Corner   NaN  New Haven   Apt. 146     USA

     Zip_Code
0       85668
1       76168
2       10058
3       20761
4       53275
...       ...
4799      NaN
4800      NaN
4801      NaN
4802      NaN
4803      NaN

[2032 rows x 7 columns]

In [301]:
# Merge office data with address data using a left join
office_data = office_expenses_addresses.copy()
office_data['Street'] = office_data['Street'].apply(lambda x: x.split(',')[0].strip())

# Assume initial phone numbers are not available and set to 'N/A'
office_data['phone_number'] = 'N/A'

import re

# Function to standardize street addresses
def standardize_address(address):
    address = address.lower().strip()  # Normalize case and strip whitespace
    address = re.sub(r'\bstreet\b', 'st', address)
    address = re.sub(r'\broad\b', 'rd', address)
    address = re.sub(r'\bavenue\b', 'ave', address)
    address = re.sub(r'\bsuite .*', '', address)  # Remove suite numbers
    return address

# Apply standardization to both dataframes
office_data['Street'] = office_data['Street'].apply(standardize_address)
combined_addresses['Street'] = combined_addresses['Street'].apply(standardize_address)

# Merge data with improved matching
joined_data = office_data.merge(
    combined_addresses[['Street', 'address_id']],
    on='Street',  # Ensure this key matches the right column
    how='left'  # Use 'left' join to keep all records from office_data
)

# Check for NaN in 'address_id' and log details
nan_address_ids = joined_data[joined_data['address_id'].isna()]

# Assuming joined_data is your final merged DataFrame from previous steps
unmatched_addresses = joined_data[joined_data['address_id'].isna()]

# Log details of unmatched addresses for review or processing
if not unmatched_addresses.empty:
    print("There are unmatched addresses that need to be reviewed or added to the addresses database.")
    print(unmatched_addresses[['Street', 'State', 'City']])

There are unmatched addresses that need to be reviewed or added to the addresses database.
                  Street State        City
184    45519 owens ramp     CT  Bridgeport
185    45519 owens ramp     CT  Bridgeport
186    45519 owens ramp     CT  Bridgeport
187    45519 owens ramp     CT  Bridgeport
188    45519 owens ramp     CT  Bridgeport
...                  ...   ...         ...
2799  40298 perez drive     NY     Buffalo
2800  40298 perez drive     NY     Buffalo
2801  40298 perez drive     NY     Buffalo
2802  40298 perez drive     NY     Buffalo
2803  40298 perez drive     NY     Buffalo

[1236 rows x 3 columns]

In [304]:
joined_data = joined_data.drop_duplicates()
joined_data

,Street,State,City,phone_number,address_id
0,09080 stone hill,CT,Bridgeport,N/A,1001.0
56,93021 charles rapid,NY,Albany,N/A,1002.0
108,9121 kevin alley,CT,Bridgeport,N/A,1003.0
184,45519 owens ramp,CT,Bridgeport,N/A,NaN
244,175 cheryl cove apt. 694,NY,Albany,N/A,NaN
320,1783 laura lakes,NJ,Jersey City,N/A,1006.0
436,207 morgan courts,NY,Syracuse,N/A,NaN
616,0503 rachel manor,CT,Bridgeport,N/A,NaN
640,78301 daugherty brooks apt. 072,CT,Hartford,N/A,NaN
832,5294 sandra spring,NY,Albany,N/A,NaN
844,65434 christopher st,NJ,Paterson,N/A,1011.0
1016,5228 kyle rapids,CT,Bridgeport,N/A,NaN
1152,921 christopher turnpike,NY,Syracuse,N/A,1013.0
1316,3824 burton meadow,NJ,Newark,N/A,1014.0
1384,73776 wilson station apt. 201,NY,Rochester,N/A,NaN
1464,6200 kelly view,NY,Albany,N/A,1016.0
1516,605 avila cliffs,NY,Albany,N/A,1017.0
1644,865 kim village,CT,Stamford,N/A,1018.0
1796,87735 heather station,CT,Hartford,N/A,1019.0
1916,5703 katherine crossing,NJ,Trenton,N/A,1020.0
1944,249 long light,NY,Syracuse,N/A,NaN
2032,2570 edward island,NJ,Paterson,N/A,NaN
2092,732 sean terrace,CT,Bridgeport,N/A,NaN
2156,9705 gary roads,CT,Waterbury,N/A,1024.0
2164,7706 gina summit,NJ,Trenton,N/A,NaN
2212,801 moore spur,NJ,Newark,N/A,1026.0
2264,34968 miller neck apt. 364,NY,New York,N/A,NaN
2336,5709 nicholas drive,CT,New Haven,N/A,1028.0
2372,90021 jerry forest,NJ,Newark,N/A,1029.0
2464,6087 romero skyway,NJ,Trenton,N/A,1030.0
2660,36136 wood stravenue,CT,Hartford,N/A,NaN
2676,40298 perez drive,NY,Buffalo,N/A,NaN

In [306]:

# Function to generate random phone numbers
def generate_phone_number():
    area_code = random.randint(200, 999)  # Valid area code
    first_part = random.randint(100, 999)
    second_part = random.randint(1000, 9999)
    return f'{area_code}-{first_part}-{second_part}'

# Apply the function to populate the phone number column where it is 'N/A'
joined_data['phone_number'] = joined_data['phone_number'].apply(lambda x: generate_phone_number() if x == 'N/A' else x)

joined_data

,Street,State,City,phone_number,address_id
0,09080 stone hill,CT,Bridgeport,270-725-6509,1001.0
56,93021 charles rapid,NY,Albany,692-958-5010,1002.0
108,9121 kevin alley,CT,Bridgeport,920-129-6053,1003.0
184,45519 owens ramp,CT,Bridgeport,331-257-5963,NaN
244,175 cheryl cove apt. 694,NY,Albany,585-862-1203,NaN
320,1783 laura lakes,NJ,Jersey City,824-597-4626,1006.0
436,207 morgan courts,NY,Syracuse,943-873-7894,NaN
616,0503 rachel manor,CT,Bridgeport,968-235-7061,NaN
640,78301 daugherty brooks apt. 072,CT,Hartford,425-459-5761,NaN
832,5294 sandra spring,NY,Albany,502-484-3390,NaN
844,65434 christopher st,NJ,Paterson,678-179-1878,1011.0
1016,5228 kyle rapids,CT,Bridgeport,953-585-9785,NaN
1152,921 christopher turnpike,NY,Syracuse,409-419-6462,1013.0
1316,3824 burton meadow,NJ,Newark,520-185-3521,1014.0
1384,73776 wilson station apt. 201,NY,Rochester,984-961-8894,NaN
1464,6200 kelly view,NY,Albany,304-909-8569,1016.0
1516,605 avila cliffs,NY,Albany,827-756-9484,1017.0
1644,865 kim village,CT,Stamford,691-568-9496,1018.0
1796,87735 heather station,CT,Hartford,987-811-7757,1019.0
1916,5703 katherine crossing,NJ,Trenton,548-597-5960,1020.0
1944,249 long light,NY,Syracuse,532-458-8484,NaN
2032,2570 edward island,NJ,Paterson,494-120-6245,NaN
2092,732 sean terrace,CT,Bridgeport,961-894-7798,NaN
2156,9705 gary roads,CT,Waterbury,602-385-9583,1024.0
2164,7706 gina summit,NJ,Trenton,827-940-1861,NaN
2212,801 moore spur,NJ,Newark,555-102-4517,1026.0
2264,34968 miller neck apt. 364,NY,New York,692-803-5826,NaN
2336,5709 nicholas drive,CT,New Haven,572-996-4501,1028.0
2372,90021 jerry forest,NJ,Newark,965-389-5848,1029.0
2464,6087 romero skyway,NJ,Trenton,547-934-7673,1030.0
2660,36136 wood stravenue,CT,Hartford,887-445-2543,NaN
2676,40298 perez drive,NY,Buffalo,883-271-1760,NaN

In [308]:
# Function to standardize addresses
def standardize_address(address):
    # Example: Convert to lowercase, replace road/street abbreviations, remove suites
    address = address.lower()
    address = address.replace('street', 'st').replace('road', 'rd')
    address = address.split(' suite')[0]
    return address.strip()

# Apply standardization
combined_addresses['Street'] = combined_addresses['Street'].apply(standardize_address)
joined_data['Street'] = joined_data['Street'].apply(standardize_address)

In [313]:
# Attempt to match addresses using exact matching first
merged_data = joined_data.merge(combined_addresses, on=['Street', 'City', 'State'], how='left')



# Unify 'address_id_x' and 'address_id_y' into a single 'address_id' column
merged_data['address_id'] = merged_data['address_id_x'].fillna(merged_data['address_id_y'])

# Optionally, if you also want to fill any remaining NaNs in 'address_id' from 'address_id_y' back into 'address_id_x'
merged_data['address_id_x'] = merged_data['address_id_x'].fillna(merged_data['address_id_y'])

# Drop the original 'address_id_x' and 'address_id_y' if they are no longer needed
merged_data.drop(['address_id_x', 'address_id_y'], axis=1, inplace=True)


merged_data

,Street,State,City,phone_number,Unit,Country,Zip_Code,address_id
0,09080 stone hill,CT,Bridgeport,270-725-6509,,USA,40398,1001.0
1,93021 charles rapid,NY,Albany,692-958-5010,,USA,11323,1002.0
2,9121 kevin alley,CT,Bridgeport,920-129-6053,,USA,63155,1003.0
3,45519 owens ramp,CT,Bridgeport,331-257-5963,Suite 211,USA,36439,1004.0
4,175 cheryl cove apt. 694,NY,Albany,585-862-1203,NaN,NaN,NaN,NaN
5,1783 laura lakes,NJ,Jersey City,824-597-4626,,USA,49729,1006.0
6,207 morgan courts,NY,Syracuse,943-873-7894,Suite 131,USA,24353,1007.0
7,0503 rachel manor,CT,Bridgeport,968-235-7061,Suite 791,USA,28518,1008.0
8,78301 daugherty brooks apt. 072,CT,Hartford,425-459-5761,NaN,NaN,NaN,NaN
9,5294 sandra spring,NY,Albany,502-484-3390,Suite 124,USA,77114,1010.0
10,65434 christopher st,NJ,Paterson,678-179-1878,,USA,97344,1011.0
11,5228 kyle rapids,CT,Bridgeport,953-585-9785,Suite 260,USA,44250,1012.0
12,921 christopher turnpike,NY,Syracuse,409-419-6462,,USA,NaN,1013.0
13,3824 burton meadow,NJ,Newark,520-185-3521,,USA,NaN,1014.0
14,73776 wilson station apt. 201,NY,Rochester,984-961-8894,NaN,NaN,NaN,NaN
15,6200 kelly view,NY,Albany,304-909-8569,,USA,NaN,1016.0
16,605 avila cliffs,NY,Albany,827-756-9484,,USA,NaN,1017.0
17,865 kim village,CT,Stamford,691-568-9496,,USA,NaN,1018.0
18,87735 heather station,CT,Hartford,987-811-7757,,USA,NaN,1019.0
19,5703 katherine crossing,NJ,Trenton,548-597-5960,,USA,NaN,1020.0
20,249 long light,NY,Syracuse,532-458-8484,Suite 896,USA,NaN,1021.0
21,2570 edward island,NJ,Paterson,494-120-6245,Suite 292,USA,NaN,1022.0
22,732 sean terrace,CT,Bridgeport,961-894-7798,Suite 820,USA,NaN,1023.0
23,9705 gary rds,CT,Waterbury,602-385-9583,,USA,NaN,1024.0
24,7706 gina summit,NJ,Trenton,827-940-1861,Suite 417,USA,NaN,1025.0
25,801 moore spur,NJ,Newark,555-102-4517,,USA,NaN,1026.0
26,34968 miller neck apt. 364,NY,New York,692-803-5826,NaN,NaN,NaN,NaN
27,5709 nicholas drive,CT,New Haven,572-996-4501,,USA,NaN,1028.0
28,90021 jerry forest,NJ,Newark,965-389-5848,,USA,NaN,1029.0
29,6087 romero skyway,NJ,Trenton,547-934-7673,,USA,NaN,1030.0
30,36136 wood stravenue,CT,Hartford,887-445-2543,Suite 798,USA,NaN,1031.0
31,40298 perez drive,NY,Buffalo,883-271-1760,Suite 835,USA,NaN,1032.0

In [312]:
missing_addresses = merged_data[merged_data['address_id'].isna()]

KeyError: 'address_id'

In [ ]:
#generating values for address_id
joined_data.insert(0, 'office_id', range(1, 1 + len(joined_data)))


joined_data['Office Name'] = office_expenses_df['Office Name']

In [40]:
offices_df = joined_data[['office_id', 'address_id', 'Office Name', 'phone_number']]
offices_df.columns = ['officeid','addressid', 'officename', 'phonenumber']
offices_df

      officeid  addressid              officename   phonenumber
0            1     1001.0  Dream Homes Bridgeport  660-542-7593
1            2     1001.0  Dream Homes Bridgeport  920-183-2459
2            3     1001.0  Dream Homes Bridgeport  698-226-3669
3            4     1001.0  Dream Homes Bridgeport  321-517-9043
4            5     1001.0  Dream Homes Bridgeport  687-122-4377
...        ...        ...                     ...           ...
2799      2800        NaN     Dream Homes Buffalo  892-469-3567
2800      2801        NaN     Dream Homes Buffalo  684-209-3250
2801      2802        NaN     Dream Homes Buffalo  464-982-8397
2802      2803        NaN     Dream Homes Buffalo  316-128-1955
2803      2804        NaN     Dream Homes Buffalo  618-384-6946

[2804 rows x 4 columns]

In [41]:
employees_df.head()

,Full Name,Email,Date of Hire,Base Salary,Office Name,Manager Name
0,"Klein, Brian",brian.klein@dreamhomes.nyc,2023-09-19,87173.68,Dream Homes Albany,"Klein, Brian"
1,"Brown, Ryan",ryan.brown@dreamhomes.nyc,2024-02-11,82936.13,Dream Homes Hartford,"Klein, Brian"
2,"Coffey, Patrick",patrick.coffey@dreamhomes.nyc,2023-01-20,36539.21,Dream Homes Bridgeport,"Brown, Ryan"
3,"Watson, Samantha",samantha.watson@dreamhomes.nyc,2023-02-16,80046.93,Dream Homes Albany,"Klein, Brian"
4,"Howard, Katherine",katherine.howard@dreamhomes.nyc,2023-10-12,49379.10,Dream Homes New York,"Brown, Ryan"

In [42]:
# Split 'Full Name' into 'firstname' and 'lastname'
employees_df[['firstname', 'lastname']] = employees_df['Full Name'].str.split(', ', expand=True)[[1, 0]]

# Ensure 'Salary' is a float (if not already)
employees_df['salary'] = employees_df['Base Salary'].astype(float)

# Create a mapping from Office Name to officeid
office_name_to_id_map = offices_df.set_index('officename')['officeid'].to_dict()

# Applying the mapping to the employees DataFrame
employees_df['officeid'] = employees_df['Office Name'].map(office_name_to_id_map)

In [43]:
#assigning random role too
role = ['Support', 'Admin', 'Agent', 'Manager']
employees_df['role'] = [random.choice(role) for _ in range(len(employees_df))]

employees_df.rename(columns={'Email': 'email'}, inplace=True)

employees_df

,Full Name,email,Date of Hire,Base Salary,Office Name,Manager Name,firstname,lastname,salary,officeid,role
0,"Klein, Brian",brian.klein@dreamhomes.nyc,2023-09-19,87173.68,Dream Homes Albany,"Klein, Brian",Brian,Klein,87173.68,1644,Manager
1,"Brown, Ryan",ryan.brown@dreamhomes.nyc,2024-02-11,82936.13,Dream Homes Hartford,"Klein, Brian",Ryan,Brown,82936.13,2676,Support
2,"Coffey, Patrick",patrick.coffey@dreamhomes.nyc,2023-01-20,36539.21,Dream Homes Bridgeport,"Brown, Ryan",Patrick,Coffey,36539.21,2156,Support
3,"Watson, Samantha",samantha.watson@dreamhomes.nyc,2023-02-16,80046.93,Dream Homes Albany,"Klein, Brian",Samantha,Watson,80046.93,1644,Support
4,"Howard, Katherine",katherine.howard@dreamhomes.nyc,2023-10-12,49379.10,Dream Homes New York,"Brown, Ryan",Katherine,Howard,49379.10,2336,Support
...,...,...,...,...,...,...,...,...,...,...,...
115,"White, Gregory",gregory.white@dreamhomes.nyc,2021-10-19,46576.68,Dream Homes Stamford,"Skinner, Aaron",Gregory,White,46576.68,1796,Support
116,"Evans, Christina",christina.evans@dreamhomes.nyc,2023-01-13,48283.19,Dream Homes Hartford,"Lowery, Michael",Christina,Evans,48283.19,2676,Agent
117,"Fry, Joseph",joseph.fry@dreamhomes.nyc,2024-04-11,104445.89,Dream Homes Syracuse,"Hines, Monica",Joseph,Fry,104445.89,2032,Admin
118,"Cruz, Pamela",pamela.cruz@dreamhomes.nyc,2023-11-30,113768.89,Dream Homes Syracuse,"Bright, Robert",Pamela,Cruz,113768.89,2032,Support
119,"Hopkins, Andrew",andrew.hopkins@dreamhomes.nyc,2023-11-04,81671.63,Dream Homes Syracuse,"Ross, Molly",Andrew,Hopkins,81671.63,2032,Manager

In [44]:
# If the phone number data isn't available, add a new column with default values
employees_df['phonenumber'] = 'N/A'  # You can use 'N/A' or another placeholder

# If you need to generate random phone numbers, use a simple logic
import random

def generate_phone_number():
    # Generate a random 10-digit phone number
    area_code = random.randint(200, 999)  # Ensures a valid area code
    first_part = random.randint(100, 999)  # Next three digits
    second_part = random.randint(1000, 9999)  # Last four digits
    return f'{area_code}-{first_part}-{second_part}'

# Apply the function to populate the phone number column
employees_df['phonenumber'] = employees_df['phonenumber'].apply(lambda x: generate_phone_number() if x == 'N/A' else x)

#generating values for employeeid
employees_df.insert(0, 'employeeid', range(1, 1 + len(employees_df)))

employees_df = employees_df [['employeeid','officeid', 'firstname', 'lastname', 'role','email','phonenumber','salary']]

employees_df

,employeeid,officeid,firstname,lastname,role,email,phonenumber,salary
0,1,1644,Brian,Klein,Manager,brian.klein@dreamhomes.nyc,535-856-7329,87173.68
1,2,2676,Ryan,Brown,Support,ryan.brown@dreamhomes.nyc,810-601-3316,82936.13
2,3,2156,Patrick,Coffey,Support,patrick.coffey@dreamhomes.nyc,564-198-2424,36539.21
3,4,1644,Samantha,Watson,Support,samantha.watson@dreamhomes.nyc,903-262-3479,80046.93
4,5,2336,Katherine,Howard,Support,katherine.howard@dreamhomes.nyc,352-399-5390,49379.10
...,...,...,...,...,...,...,...,...
115,116,1796,Gregory,White,Support,gregory.white@dreamhomes.nyc,470-528-9499,46576.68
116,117,2676,Christina,Evans,Agent,christina.evans@dreamhomes.nyc,869-632-9643,48283.19
117,118,2032,Joseph,Fry,Admin,joseph.fry@dreamhomes.nyc,582-461-1713,104445.89
118,119,2032,Pamela,Cruz,Support,pamela.cruz@dreamhomes.nyc,859-319-1720,113768.89
119,120,2032,Andrew,Hopkins,Manager,andrew.hopkins@dreamhomes.nyc,861-881-4227,81671.63

In [45]:
clients_df.head()

,Name,Email,Phone Number,Street,State,Zip Code,Client Type,Preferred Home Type,Preferred Number of Bedrooms,Preferred Number of Bathrooms,Preferred Square Footage,Preferred School Rating,Assigned Employee
0,"Melton, Ashley",ashley.melton@example.com,6076274707,549 Nguyen Underpass Suite 698,NY,13309,buyer,condo,5.0,3.0,2775.0,5.0,"Tanner, Sean"
1,"Cooley, Melissa",melissa.cooley@example.com,292-810-9738,44362 Dennis Hill,CT,6205,buyer,single house,1.0,1.0,1812.0,6.0,"Mcguire, Jeanette"
2,"Gibbs, Angela",angela.gibbs@example.com,001-766-553-7400,9515 Joseph Manor Apt. 900,NY,10370,owner,NaN,NaN,NaN,NaN,NaN,"Davis, Ashley"
3,"Gardner, Jasmine",jasmine.gardner@example.com,535.355.1974x252,273 Bernard Ports Apt. 062,NJ,8790,renter,condo,5.0,2.0,2498.0,2.0,"Rios, Mary"
4,"Castro, Charles",charles.castro@example.com,511.384.1001x42377,45976 Stone Squares Apt. 678,NY,14496,owner,NaN,NaN,NaN,NaN,NaN,"Rios, Mary"

In [46]:
# Split 'Name' into 'firstname' and 'lastname'
clients_df[['firstname', 'lastname']] = clients_df['Name'].str.split(', ', expand=True)[[1, 0]]

# Rename and reformat necessary columns
clients_df['clienttype'] = clients_df['Client Type'].map({
    'buyer': 'buyer', 
    'seller': 'seller', 
    'renter': 'renter', 
    'owner': 'owner'
})

clients_df.rename(columns={'Email': 'email'}, inplace=True)
clients_df.rename(columns={'Phone Number': 'phonenumber'}, inplace=True)

#generating values for clientid
clients_df.insert(0, 'clientid', range(1, 1 + len(clients_df)))

clients_df = clients_df [[ 'clientid', 'firstname', 'lastname','email','phonenumber', 'clienttype']]

# Display the first few entries to verify changes
clients_df.head()

,clientid,firstname,lastname,email,phonenumber,clienttype
0,1,Ashley,Melton,ashley.melton@example.com,6076274707,buyer
1,2,Melissa,Cooley,melissa.cooley@example.com,292-810-9738,buyer
2,3,Angela,Gibbs,angela.gibbs@example.com,001-766-553-7400,owner
3,4,Jasmine,Gardner,jasmine.gardner@example.com,535.355.1974x252,renter
4,5,Charles,Castro,charles.castro@example.com,511.384.1001x42377,owner

In [264]:
home_listings_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/home_listings.csv')
home_listings_df

,Listing ID,Title,Description,Home Type,Bedrooms,Bathrooms,Year Built,Square Footage,Listed Price,Listing Type,Amenities,Street,City,Zip Code,Commute Options,Listing Date,Nearby Schools,Utilities,Owner/Seller Name
0,8585561689,Charming 4-Bedroom Townhouse with parking,This charming 4-bedroom townhouse offers a spa...,Townhouse,4,2,1985,2446,4125,Rent,"['parking', 'patio', 'fireplace', 'doorman', '...",56162 Omar Park,New York,10060,"['Bus 103', 'Bus 101']",2021-05-05,"[{'name': 'Jackson, Smith and Williams', 'rati...",['Verizon'],"Wiggins, Michael"
1,1550678141,Luxurious 3-Bedroom Townhouse with parking,This luxurious 3-bedroom townhouse offers a sp...,Townhouse,3,2,1921,1853,923862,Sale,"['pool', 'gym', 'fireplace', 'patio', 'parking']",466 Dawson Terrace Apt. 858,New York,11033,"['Train A', 'Train B', 'Bus 101']",2022-01-24,"[{'name': 'Wilson Inc', 'rating': 8}, {'name':...","['Optimum', 'Spectrum']","Chavez, Lisa"
2,8476052241,Charming 1-Bedroom Apartment with pool,This charming 1-bedroom apartment offers a spa...,Apartment,1,3,1902,3077,4310,Rent,"['patio', 'gym', 'parking', 'pool', 'doorman']",9026 Chad Valley,Buffalo,10410,['Bus 101'],2021-07-17,"[{'name': 'Weaver-Vargas', 'rating': 0}, {'nam...",['Optimum'],"Bruce, Chris"
3,2107612233,Charming 3-Bedroom Townhouse with parking,This charming 3-bedroom townhouse offers a spa...,Townhouse,3,2,2011,2079,2664,Rent,"['patio', 'gym', 'parking']",827 Santos Stream,Elizabeth,7725,"['Bus 102', 'Train B', 'Bus 103']",2023-09-10,"[{'name': 'Baker-Potter', 'rating': 8}, {'name...","['Spectrum', 'Con Edison', 'National Grid']","Sandoval, Victoria"
4,4929040086,Luxurious 3-Bedroom Condo with pool,This luxurious 3-bedroom condo offers a spacio...,Condo,3,1,1929,1712,781721,Sale,"['patio', 'fireplace', 'pool', 'parking']",3635 Alison Bridge,Stamford,6119,['Train B'],2024-02-15,"[{'name': 'Fletcher, Poole and Alvarez', 'rati...",['Verizon'],"Bryant, Kaitlyn"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,7919467850,Luxurious 5-Bedroom Townhouse with doorman,This luxurious 5-bedroom townhouse offers a sp...,Townhouse,5,1,1977,908,1231441,Sale,"['doorman', 'parking', 'pool', 'fireplace']",28291 Brandon Stravenue,Syracuse,13271,['Bus 103'],2022-05-26,"[{'name': 'Montgomery-Waters', 'rating': 3}]","['Verizon', 'Optimum']","Oliver, Matthew"
996,9775018591,Charming 3-Bedroom Townhouse with patio,This charming 3-bedroom townhouse offers a spa...,Townhouse,3,2,2014,1019,3652,Rent,"['doorman', 'patio']",13328 Waters Ford Suite 061,New York,12965,"['Train A', 'Bus 102']",2021-12-20,"[{'name': 'Knapp, Jacobson and Valdez', 'ratin...","['Con Edison', 'National Grid', 'Verizon']","Scott, Erica"
997,6429659679,Luxurious 1-Bedroom Single Family Home with gym,This luxurious 1-bedroom single family home of...,Single Family Home,1,2,1914,2821,488191,Sale,"['gym', 'parking', 'pool']",033 Wilson Isle Suite 690,Buffalo,11266,['Train A'],2022-10-08,"[{'name': 'Rodriguez LLC', 'rating': 1}, {'nam...",['Spectrum'],"Combs, Mary"
998,1858711056,Charming 3-Bedroom Townhouse with parking,This charming 3-bedroom townhouse offers a spa...,Townhouse,3,2,1965,1167,4081,Rent,"['patio', 'parking', 'gym', 'pool', 'fireplace']",7457 Paula Pines,New Haven,6077,"['Bus 103', 'Train C']",2023-01-11,"[{'name': 'Maldonado, Smith and Fernandez', 'r...","['Optimum', 'National Grid']","Rojas, Kim"
999,1828375380,Charming 4-Bedroom Apartment with doorman,This charming 4-bedroom apartment offers a spa...,Apartment,4,1,2008,553,2836,Rent,"['patio', 'fireplace', 'pool', 'doorman']",92007 Michael Corner Apt. 146,New Haven,6056,['Bus 103'],2023-04-13,"[{'name': 'Smith-Good', 'rating': 8}, {'name':...","['National Grid', 'Optimum', 'PSE&G']","Martinez, Robert"

In [265]:
import pandas as pd
from datetime import datetime

home_listings_df['homeid'] = (home_listings_df['Listing ID'])
home_listings_df['listingdate'] = pd.to_datetime(home_listings_df['Listing Date'])
home_listings_df['price'] = home_listings_df['Listed Price']
home_listings_df['status'] = home_listings_df['Listing Type']
home_listings_df['bedroomcount'] = home_listings_df['Bedrooms']
home_listings_df['bathroomcount'] = home_listings_df['Bathrooms']
home_listings_df['squarefootage'] = home_listings_df['Square Footage']

# Define a function to handle address to address_id mapping if needed
def map_address_to_id(row):
    # Implement logic to determine address_id based on address components
    return hash(f"{row['Street']} {row['City']} {row['Zip Code']}") % 10000  # Example hash-based placeholder

home_listings_df['addressid'] = home_listings_df.apply(map_address_to_id, axis=1)

sellers_df = clients_df[['clientid', 'firstname', 'lastname']].copy()

sellers_df['Full Name'] = sellers_df['lastname'] + ', ' + sellers_df['firstname']

# Create a mapping from Office Name to officeid
seller_name_to_id = sellers_df.set_index('Full Name')['clientid'].to_dict()

# Apply this mapping to the 'Owner/Seller Name' column in home_listings_df to get 'sellerid'
home_listings_df['sellerid'] = home_listings_df['Owner/Seller Name'].map(seller_name_to_id)


home_listings_df = home_listings_df [['homeid','addressid','sellerid','listingdate','price','status','bedroomcount','bathroomcount','squarefootage']]


home_listings_df

,homeid,addressid,sellerid,listingdate,price,status,bedroomcount,bathroomcount,squarefootage
0,8585561689,1245,755,2021-05-05,4125,Rent,4,2,2446
1,1550678141,3619,951,2022-01-24,923862,Sale,3,2,1853
2,8476052241,5158,272,2021-07-17,4310,Rent,1,3,3077
3,2107612233,3604,357,2023-09-10,2664,Rent,3,2,2079
4,4929040086,8664,550,2024-02-15,781721,Sale,3,1,1712
...,...,...,...,...,...,...,...,...,...
995,7919467850,5705,543,2022-05-26,1231441,Sale,5,1,908
996,9775018591,6822,73,2021-12-20,3652,Rent,3,2,1019
997,6429659679,9762,561,2022-10-08,488191,Sale,1,2,2821
998,1858711056,3664,145,2023-01-11,4081,Rent,3,2,1167
999,1828375380,3452,185,2023-04-13,2836,Rent,4,1,553

In [266]:
value_to_check = 4251196064
is_value_in_column = home_listings_df['homeid'].isin([value_to_check]).any()
print(f"Is {value_to_check} in homeid? {is_value_in_column}")

Is 4251196064 in homeid? True

In [49]:
# List of all possible amenities
amenities_list = [
    'Pool', 'Gym', 'Balcony', 'Laundry', 'Parking', 'Fireplace', 'Doorman', 'Patio',
    'Storage', 'Garden', 'Roof Deck', 'Bike Room', 'Elevator', 'Pet Friendly',
    'Walk-in Closet', 'Washer/Dryer', 'Central Air', 'Dishwasher', 'Hardwood Floors'
]

# Convert each amenity in the list to lowercase
amenities_list = [amenity.lower() for amenity in amenities_list]

# Create DataFrame for amenities
amenities_df = pd.DataFrame({
    'amenityid': range(1, len(amenities_list) + 1),
    'amenitytype': amenities_list
})

amenities_df

    amenityid      amenitytype
0           1             pool
1           2              gym
2           3          balcony
3           4          laundry
4           5          parking
5           6        fireplace
6           7          doorman
7           8            patio
8           9          storage
9          10           garden
10         11        roof deck
11         12        bike room
12         13         elevator
13         14     pet friendly
14         15   walk-in closet
15         16     washer/dryer
16         17      central air
17         18       dishwasher
18         19  hardwood floors

In [50]:
import pandas as pd
import ast  # To safely evaluate string literal as a Python list

home_listings_df2 = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/home_listings.csv')

# Convert 'Amenities' from string representation of a list to an actual list
home_listings_df2['Amenities'] = home_listings_df2['Amenities'].apply(lambda x: ast.literal_eval(x))

# Explode the 'Amenities' column into separate rows
amenities_expanded = home_listings_df2.explode('Amenities')

amenities_df['amenitytype'] = amenities_df['amenitytype'].str.strip()
amenities_expanded['Amenities'] = amenities_expanded['Amenities'].str.strip()

# Prepare the mapping from amenity type to amenity ID
amenity_to_id = amenities_df.set_index('amenitytype')['amenityid'].to_dict()

# Apply the mapping to the exploded DataFrame to replace amenity descriptions with IDs
amenities_expanded['amenityid'] = amenities_expanded['Amenities'].map(amenity_to_id)

# Copy 'Listing ID' to a new column 'homeid'
amenities_expanded['homeid'] = amenities_expanded['Listing ID']

#generating values for clientid
amenities_expanded.insert(0, 'id', range(1, 1 + len(amenities_expanded)))

home_id_amenities_df = amenities_expanded [['id','homeid','amenityid']]

home_id_amenities_df

       id      homeid  amenityid
0       1  8585561689          5
0       2  8585561689          8
0       3  8585561689          6
0       4  8585561689          7
0       5  8585561689          2
..    ...         ...        ...
998  3540  1858711056          6
999  3541  1828375380          8
999  3542  1828375380          6
999  3543  1828375380          1
999  3544  1828375380          7

[3544 rows x 3 columns]

In [51]:

# Define a safe parsing function for the 'Nearby Schools' column
def parse_schools(schools_str):
    try:
        return ast.literal_eval(schools_str)
    except Exception as e:
        return []  # Return an empty list in case of an error

home_listings_df2 = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/home_listings.csv')

# Apply the parsing function to the 'Nearby Schools' column
home_listings_df2['Nearby Schools Parsed'] = home_listings_df2['Nearby Schools'].apply(parse_schools)

# Explode the parsed lists into separate rows
schools_expanded = home_listings_df2.explode('Nearby Schools Parsed')

# Extract school names and other data if available
schools_expanded['School Name'] = schools_expanded['Nearby Schools Parsed'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)
schools_expanded['School Rating'] = schools_expanded['Nearby Schools Parsed'].apply(lambda x: x.get('rating') if isinstance(x, dict) and 'rating' in x else None)

# Create a DataFrame for neighborhoodfeatures
neighborhood_features_df = pd.DataFrame({
    'featuretype': 'School',
    'featurename': schools_expanded['School Name']
})

# Removing duplicates
neighborhood_features_df = neighborhood_features_df.drop_duplicates(subset=['featurename']).reset_index(drop=True)


#generating values for clientid
neighborhood_features_df.insert(0, 'featureid', range(1, 1 + len(neighborhood_features_df)))

# Display the DataFrame to verify
print(neighborhood_features_df)

      featureid featuretype                     featurename
0             1      School     Jackson, Smith and Williams
1             2      School                      Wilson Inc
2             3      School          Brown, Martin and Mann
3             4      School                       Burns Inc
4             5      School                   Weaver-Vargas
...         ...         ...                             ...
1893       1894      School    Kelly, Joseph and Washington
1894       1895      School  Maldonado, Smith and Fernandez
1895       1896      School      Brown, Jackson and Hensley
1896       1897      School                      Smith-Good
1897       1898      School                   Rodriguez PLC

[1898 rows x 3 columns]

In [52]:
home_listings_df2 = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/home_listings.csv')

# Assuming Nearby Schools are stored as a string that looks like a list of dictionaries
def parse_nearby_schools(schools_str):
    try:
        # Safely parse the string into a list of dictionaries
        schools_list = ast.literal_eval(schools_str)
        if isinstance(schools_list, list) and schools_list:
            return schools_list[0]['name']  # Assuming you want to extract the name of the first school
    except:
        return None  # Return None if parsing fails or data is not as expected

# Apply the parsing function
home_listings_df2['Nearest School'] = home_listings_df2['Nearby Schools'].apply(parse_nearby_schools)

# Create a dictionary mapping from featurename to featureid
feature_name_to_id = neighborhood_features_df.set_index('featurename')['featureid'].to_dict()

home_listings_df2['featureid'] = home_listings_df2['Nearest School'].map(feature_name_to_id)

# Select only the necessary columns for the new table
home_neighborhood_features_df = home_listings_df2[['Listing ID', 'featureid']]
home_neighborhood_features_df.columns = ['homeid', 'featureid']  # Rename columns appropriately

#generating values for clientid
home_neighborhood_features_df.insert(0, 'id', range(1, 1 + len(home_neighborhood_features_df)))

# Display to verify
home_neighborhood_features_df

       id      homeid  featureid
0       1  8585561689          1
1       2  1550678141          2
2       3  8476052241          5
3       4  2107612233          7
4       5  4929040086          9
..    ...         ...        ...
995   996  7919467850       1890
996   997  9775018591       1891
997   998  6429659679        286
998   999  1858711056       1895
999  1000  1828375380       1897

[1000 rows x 3 columns]

In [175]:
transactions_df = pd.read_csv('/Users/dave.john.98/Desktop/APAN/Spring_24/SQL/Group Project/Sample Data/transactions.csv')
transactions_df

,Listing ID,Employee Name,Client Name,Date of Transaction,Status,Final Price,Agent Fee Percentage
0,8585561689,"Leon, Patrick","Torres, Robert",2021-05-16,pending rental,NaN,NaN
1,8585561689,"Leon, Patrick","Torres, Robert",2021-06-09,rented,4502.79,100.000000
2,1550678141,"Olson, Andrea","Cox, Megan",2022-01-29,pending sale,NaN,NaN
3,1550678141,"Olson, Andrea","Cox, Megan",2022-02-22,sold,972329.33,4.356721
4,8476052241,"Simpson, Christina","Thompson, Tammy",2021-07-25,pending rental,NaN,NaN
...,...,...,...,...,...,...,...
1995,6429659679,"Johnson, Angelica",NaN,2022-11-14,relisted,NaN,NaN
1996,1858711056,"Mcguire, Jeanette","Mosley, Mary",2023-01-19,pending rental,NaN,NaN
1997,1858711056,"Mcguire, Jeanette","Mosley, Mary",2023-02-15,rented,4155.69,100.000000
1998,1828375380,"Shaffer, Jacqueline","Jones, Andrew",2023-04-17,pending rental,NaN,NaN
1999,1828375380,"Shaffer, Jacqueline","Jones, Andrew",2023-05-09,rented,3096.90,100.000000

In [177]:
transactions_df.rename(columns={'Listing ID': 'homeid', 'Final Price': 'amount', 
                                'Date of Transaction':'date' }, inplace=True)

#assigning random transactiontype
transactiontype = ['Sale', 'Rent']
transactions_df['transactiontype'] = [random.choice(transactiontype) for _ in range(len(transactions_df))]

# For clients_df

clients_df2 = clients_df
clients_df2['Client Name'] = clients_df2['lastname'].str.strip() + ', ' + clients_df2['firstname'].str.strip()


# For employees_df
employees_df2 = employees_df.copy()
employees_df2['Employee Name'] = employees_df2['lastname'].str.strip() + ', ' + employees_df2['firstname'].str.strip()

                                                                                   
# Create mapping from client names to client IDs
client_name_to_id = clients_df2.set_index('Client Name')['clientid'].to_dict()

# Create mapping from employee names to employee IDs
employee_name_to_id = employees_df2.set_index('Employee Name')['employeeid'].to_dict()

# Apply the mapping to the transaction data
transactions_df['buyerid'] = transactions_df['Client Name'].map(client_name_to_id)
transactions_df['sellerid'] = transactions_df['Client Name'].map(client_name_to_id)  # Assuming the same mapping for simplicity
transactions_df['employeeid'] = transactions_df['Employee Name'].map(employee_name_to_id)


#generating values for transactionid
transactions_df.insert(0, 'transactionid', range(1, 1 + len(transactions_df)))


past_transactions_df = transactions_df[['transactionid','homeid', 'buyerid', 'sellerid', 'employeeid', 'date', 'amount', 'transactiontype']]

In [178]:
past_transactions_df

,transactionid,homeid,buyerid,sellerid,employeeid,date,amount,transactiontype
0,1,8585561689,15.0,15.0,106,2021-05-16,NaN,Sale
1,2,8585561689,15.0,15.0,106,2021-06-09,4502.79,Sale
2,3,1550678141,787.0,787.0,86,2022-01-29,NaN,Sale
3,4,1550678141,787.0,787.0,86,2022-02-22,972329.33,Sale
4,5,8476052241,247.0,247.0,48,2021-07-25,NaN,Rent
...,...,...,...,...,...,...,...,...
1995,1996,6429659679,NaN,NaN,39,2022-11-14,NaN,Rent
1996,1997,1858711056,162.0,162.0,88,2023-01-19,NaN,Rent
1997,1998,1858711056,162.0,162.0,88,2023-02-15,4155.69,Rent
1998,1999,1828375380,860.0,860.0,60,2023-04-17,NaN,Rent
1999,2000,1828375380,860.0,860.0,60,2023-05-09,3096.90,Rent

In [267]:
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()

# Helper functions
def random_date(start, end):
    """Generate a random date between start and end."""
    return (start + timedelta(
        seconds=random.randint(0, int((end - start).total_seconds())))).date()


# Generate data for PropertyMaintenanceRequests
property_maintenance_requests_df = pd.DataFrame({
    'maintenancerequestid': range(1, 151),
    'homeid': random.choices(home_listings_df['homeid'].tolist(), k=150),  # Valid home IDs
    'requestdate': [random_date(datetime(2020, 1, 1), datetime(2023, 12, 31)) for _ in range(150)],
    'issuedescription': [fake.sentence() for _ in range(150)],
    'urgencylevel': random.choices(['Low', 'Medium', 'High'], weights=[30, 50, 20], k=150),
    'resolutionstatus': random.choices(['Pending', 'In Progress', 'Completed'], weights=[40, 30, 30], k=150)
})

property_maintenance_requests_df

,maintenancerequestid,homeid,requestdate,issuedescription,urgencylevel,resolutionstatus
0,1,6865394995,2021-02-13,List total community defense although.,High,In Progress
1,2,1321031354,2022-11-11,Bad fear fall early.,Low,In Progress
2,3,6377738404,2020-11-22,Time traditional character choice middle small...,High,Pending
3,4,4649857187,2020-10-23,Position ahead join sign also big set.,High,Pending
4,5,2665693396,2022-12-16,Democrat strong politics produce way eat famil...,Medium,In Progress
...,...,...,...,...,...,...
145,146,9859529509,2020-01-14,Air three city wonder man assume spring.,Medium,Completed
146,147,3967942322,2021-10-21,Three still for soon response risk.,High,Completed
147,148,2398598262,2023-11-20,Also learn fight professional door could.,Medium,In Progress
148,149,1813452304,2021-10-22,Enjoy baby learn story view practice.,Medium,Pending
149,150,1745751442,2023-08-14,Building most true fish culture.,Medium,Completed

In [56]:
transactions_df2 = transactions_df.copy() [['transactionid','employeeid','date',]]


# Create a dictionary mapping employeeID to officeID
employee_to_office = employees_df.set_index('employeeid')['officeid'].to_dict()

transactions_df2['officeid'] = transactions_df2['employeeid'].map(employee_to_office)

# Add a new column 'type' with randomly generated data
transactions_df2['type'] = random.choices(['Revenue', 'Expense', 'Commission'], weights=[40, 30, 30],k=len(transactions_df2))
transactions_df2['notes'] = [fake.sentence() if random.random() > 0.5 else None for _ in range(len(transactions_df2))]


#generating values for transactionid
transactions_df2.insert(0, 'recordid', range(1, 1 + len(transactions_df2)))

financial_records_df = transactions_df2 [['recordid','date','type', 'notes','transactionid', 'employeeid','officeid']]

financial_records_df

,recordid,date,type,notes,transactionid,employeeid,officeid
0,1,2021-05-16,Revenue,None,1,106,2156
1,2,2021-06-09,Revenue,None,2,106,2156
2,3,2022-01-29,Commission,None,3,86,2032
3,4,2022-02-22,Expense,Recent science hotel difference traditional re...,4,86,2032
4,5,2021-07-25,Expense,Movement church policy simple.,5,48,2804
...,...,...,...,...,...,...,...
1995,1996,2022-11-14,Commission,None,1996,39,1644
1996,1997,2023-01-19,Commission,Kitchen you region another both.,1997,88,2660
1997,1998,2023-02-15,Revenue,Media bill near.,1998,88,2660
1998,1999,2023-04-17,Revenue,Easy put expert also present.,1999,60,436
1999,2000,2023-05-09,Revenue,None,2000,60,436

In [57]:
# 11. Generate data for Appointments
appointments_df = pd.DataFrame({
    'appointmentid': range(1, 601),
    'clientid': random.choices(clients_df['clientid'].tolist(), k=600),  # Valid client IDs
    'employeeid': random.choices(employees_df['employeeid'].tolist(), k=600),  # Valid employee IDs
    'date': [random_date(datetime(2020, 1, 1), datetime(2023, 12, 31)) for _ in range(600)],
    'time': [fake.time() for _ in range(600)],
    'purpose': random.choices(['Viewing', 'Consultation', 'Closing'], weights=[50, 30, 20], k=600),
    'notes': [fake.sentence() if random.random() > 0.5 else None for _ in range(600)]  # Randomly include or exclude notes
})

appointments_df

,appointmentid,clientid,employeeid,date,time,purpose,notes
0,1,403,3,2020-03-01,04:34:25,Consultation,Mouth yes skill parent.
1,2,2,44,2020-03-23,13:26:36,Closing,None
2,3,632,96,2022-10-30,22:41:26,Consultation,None
3,4,455,25,2023-07-18,03:18:01,Consultation,None
4,5,265,109,2021-12-16,03:18:50,Consultation,Cause woman value another technology college.
...,...,...,...,...,...,...,...
595,596,478,91,2020-02-23,02:46:32,Viewing,None
596,597,480,4,2022-05-01,03:54:52,Closing,None
597,598,217,79,2021-12-09,15:51:23,Viewing,Including these movie technology wait sort.
598,599,615,92,2022-08-06,04:52:15,Closing,Because either crime part thousand.
599,600,603,98,2023-07-14,08:14:13,Viewing,Sure give stop situation partner but.

In [58]:
 # Generate data for ClientInquiries
client_inquiries_df = pd.DataFrame({
    'InquiryID': range(1, 2001),
    'clientid': random.choices(clients_df['clientid'].tolist(), k=2000),  # Valid client IDs
    'date': [random_date(datetime(2020, 1, 1), datetime(2023, 1, 1)) for _ in range(2000)],
    'inquirytype': random.choices(['General', 'Specific Home', 'Investment'], weights=[40, 40, 20], k=2000),
    'description': [fake.sentence() for _ in range(2000)]
})

client_inquiries_df

,InquiryID,clientid,date,inquirytype,description
0,1,996,2020-02-21,Investment,Think usually may recognize.
1,2,135,2021-12-23,Specific Home,News scene large good reality front.
2,3,842,2021-05-25,General,First listen hot range.
3,4,815,2021-06-06,Specific Home,Tell real must station we someone.
4,5,222,2021-04-11,Investment,Exist feel world police positive often remain ...
...,...,...,...,...,...
1995,1996,387,2021-09-28,Specific Home,Make task recent increase senior.
1996,1997,241,2022-07-15,General,Ok recent view society.
1997,1998,271,2022-03-10,General,Read environment research site draw off.
1998,1999,311,2020-02-05,General,Beyond war religious occur center bad.
1999,2000,792,2021-09-22,Investment,Accept event college.

In [59]:
fake = Faker()  # Initialize Faker to generate fake data

def random_date(start, end):
    """Generate a random datetime between `start` and `end`."""
    return start + timedelta(
        seconds=random.randint(0, int((end - start).total_seconds())),
    )

# Generate lists for starttime and endtime
start_times = [fake.time() for _ in range(80)]
end_times = []

for time_str in start_times:
    start_time = datetime.strptime(time_str, '%H:%M:%S')
    end_time = start_time + timedelta(hours=random.randint(2, 6))
    end_times.append(end_time.strftime('%H:%M:%S'))

# Generate data for OpenHouses
open_houses_df = pd.DataFrame({
    'openhouseid': range(1, 81),
    'homeid': random.choices(home_listings_df['homeid'].tolist(), k=80), 
    'date': [random_date(datetime(2020, 1, 1), datetime(2023, 12, 31)) for _ in range(80)],
    'starttime': start_times,
    'endtime': end_times,
    'notes': [fake.sentence() if random.random() > 0.5 else None for _ in range(80)]
})

# Display the DataFrame
open_houses_df

,openhouseid,homeid,date,starttime,endtime,notes
0,1,1421942427,2020-07-02 07:36:02,17:54:01,23:54:01,None
1,2,4352473165,2022-10-17 02:54:43,13:16:24,18:16:24,None
2,3,1508892460,2020-02-12 09:38:10,23:36:42,03:36:42,Money successful good significant style.
3,4,4578946712,2023-10-08 18:53:05,04:21:19,10:21:19,Son particularly participant culture huge atto...
4,5,9850153889,2023-05-20 03:17:12,08:34:53,12:34:53,None
...,...,...,...,...,...,...
75,76,5094598910,2021-04-25 21:13:00,08:48:14,11:48:14,None
76,77,6176083691,2020-02-18 21:11:18,16:14:39,19:14:39,None
77,78,1856880855,2021-05-02 08:03:28,00:18:57,06:18:57,Final capital analysis section most.
78,79,8471862726,2022-02-11 04:48:45,07:33:27,11:33:27,Woman family write project shoulder.
79,80,7314189443,2022-12-12 16:35:17,08:42:46,14:42:46,Administration his economy age chance communit...

In [60]:
user_favorites_df = pd.DataFrame({
    'userid': random.choices(clients_df['clientid'].tolist(), k=300),  # Valid client IDs
    'homeid': random.choices(home_listings_df['homeid'].tolist(), k=300),  # Valid home IDs
    'FavoritedOnDate': [random_date(datetime(2020, 1, 1), datetime(2023, 1, 1)) for _ in range(300)]
})


user_favorites_df

     userid      homeid     FavoritedOnDate
0       552  9579006329 2020-07-14 09:06:25
1       678  2970238604 2022-12-04 22:38:07
2       818  6294540070 2022-07-01 19:36:50
3       176  4441804088 2022-09-07 11:18:47
4       733  5511678597 2020-12-14 14:12:29
..      ...         ...                 ...
295     117  3982802982 2021-01-27 09:05:47
296      86  2497464311 2022-12-19 23:43:09
297     447  2630626433 2022-04-19 09:24:23
298     131  1087279822 2022-04-17 04:13:37
299     391  8584942181 2020-05-10 16:44:37

[300 rows x 3 columns]

In [61]:
!pip install sqlalchemy
!pip install psycopg2-binary
!pip install alembic

Requirement already satisfied: sqlalchemy in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: psycopg2-binary in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (2.9.9)
Requirement already satisfied: alembic in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (1.13.1)
Requirement already satisfied: SQLAlchemy>=1.3.0 in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (from alembic) (1.4.39)
Requirement already satisfied: Mako in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (from alembic) (1.3.2)
Requirement already satisfied: typing-extensions>=4 in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (from alembic) (4.7.1)
Requirement already satisfied: greenlet!=0.4.17 in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (from SQLAlchemy>=1.3.0->alembic) (2.0.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /Users/dave.john.98/anaconda3/lib/python3.11/site-packages (from Mako->alembic) (2.1.1)

In [62]:
from sqlalchemy import create_engine

In [269]:
# Pass the connection string to a variable, conn_url
conn_url = 'postgresql://postgres:123@localhost/SQL_FINAL_PROJECT'

# Create an engine that connects to PostgreSQL server
engine = create_engine(conn_url)

# Establish a connection
connection = engine.connect()

In [270]:
# Pass the SQL statements that create all tables
stmt = """
CREATE TABLE addresses (
    address_id SERIAL PRIMARY KEY,
    street VARCHAR(255),
    unit VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code CHAR(5) NOT NULL,
    country VARCHAR(50)NOT NULL
);

CREATE TABLE offices (
    officeid SERIAL PRIMARY KEY,
    addressid INT,
    officename VARCHAR(255),
    phonenumber VARCHAR(20),
    FOREIGN KEY (addressid) REFERENCES addresses(address_id)
);

CREATE TABLE employees (
    employeeid SERIAL PRIMARY KEY,
    officeid INT,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    role VARCHAR(100),
    email VARCHAR(255) NOT NULL,
    phonenumber VARCHAR(20),
    salary DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (officeid) REFERENCES offices(officeid)
);

CREATE TABLE clients (
    clientid SERIAL PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phonenumber VARCHAR(250),
    clienttype VARCHAR(50) NOT NULL
);

CREATE TABLE amenities (
    amenityid SERIAL PRIMARY KEY,
    amenitytype VARCHAR(60) NOT NULL UNIQUE
    );

CREATE TABLE neighborhoodfeatures (
    featureid SERIAL PRIMARY KEY,
    featuretype VARCHAR(150),
    featurename TEXT
    );

CREATE TABLE home_listings (
    homeid BIGINT PRIMARY KEY,
    addressid INT NOT NULL,
    sellerid INT NOT NULL,
    listingdate DATE NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    bedroomcount INT NOT NULL,
    bathroomcount INT NOT NULL,
    squarefootage INT NOT NULL,
    FOREIGN KEY (addressid) REFERENCES addresses(address_id),
    FOREIGN KEY (sellerid) REFERENCES clients(clientid)
);

CREATE TABLE home_id_amenities (
    id SERIAL PRIMARY KEY,
    homeid BIGINT NOT NULL,
    amenityid INT NOT NULL,
    FOREIGN KEY (homeid) REFERENCES home_listings(homeid),
    FOREIGN KEY (amenityid) REFERENCES amenities(amenityid)
);

CREATE TABLE home_neighborhood_features (
    id SERIAL PRIMARY KEY,
    homeid BIGINT NOT NULL,
    featureid INT NOT NULL,
    FOREIGN KEY (homeid) REFERENCES home_listings(homeid),
    FOREIGN KEY (featureid) REFERENCES neighborhoodfeatures(featureid)
);

CREATE TABLE past_transactions (
    transactionid SERIAL PRIMARY KEY,
    homeid BIGINT NOT NULL,
    buyerid INT NOT NULL,
    sellerid INT NOT NULL,
    employeeid INT NOT NULL,
    date TIMESTAMP NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    transactiontype VARCHAR(50) NOT NULL,
    FOREIGN KEY (homeid) REFERENCES home_listings(homeid),
    FOREIGN KEY (buyerid) REFERENCES clients(clientid),
    FOREIGN KEY (sellerid) REFERENCES clients(clientid),
    FOREIGN KEY (employeeid) REFERENCES employees(employeeid)
);

CREATE TABLE financial_records (
    recordid SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    type VARCHAR(100) NOT NULL,
    notes TEXT NULL,
    transactionid INT NOT NULL,
    employeeid INT NOT NULL,
    officeid INT NOT NULL,
    FOREIGN KEY (transactionid) REFERENCES past_transactions(transactionid),
    FOREIGN KEY (employeeid) REFERENCES employees(employeeid),
    FOREIGN KEY (officeid) REFERENCES offices(officeid)
);

CREATE TABLE client_inquiries (
    inquiryid SERIAL PRIMARY KEY,
    clientid INT NOT NULL,
    date TIMESTAMP NOT NULL,
    inquirytype VARCHAR(100),
    description TEXT,
    FOREIGN KEY (clientid) REFERENCES clients(clientid)
);

CREATE TABLE appointments (
    appointmentid INT PRIMARY KEY,
    clientid INT NOT NULL,
    employeeid INT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    notes TEXT,
    FOREIGN KEY (clientid) REFERENCES clients(clientid),
    FOREIGN KEY (employeeid) REFERENCES employees(employeeid)
);

CREATE TABLE user_favorites (
    userid INT,
    homeid INT,
    favoritedondate DATE NOT NULL,
    PRIMARY KEY(userid, homeid),
    FOREIGN KEY (userid) REFERENCES clients(clientid),
    FOREIGN KEY (homeid) REFERENCES home_listings(homeid)
);

CREATE TABLE open_houses (
    openhouseid SERIAL PRIMARY KEY,
    homeid INT NOT NULL,
    date DATE NOT NULL,
    starttime TIME,
    endtime TIME,
    notes TEXT,
    FOREIGN KEY (homeID) REFERENCES home_listings(homeID)
);

CREATE TABLE property_maintenance_requests (
    maintenancerequestid SERIAL PRIMARY KEY,
    homeid BIGINT NOT NULL,
    requestdate TIMESTAMP NOT NULL,
    issuedescription TEXT NOT NULL,
    urgencylevel VARCHAR(50) NOT NULL,
    resolutionstatus VARCHAR(100) NOT NULL,
    FOREIGN KEY (homeid) REFERENCES home_listings(homeid)
);


"""

# Execute the statement to create tables
connection.execute(stmt)

In [271]:
combined_addresses.columns = [col.lower() for col in combined_addresses.columns]

combined_addresses

,address_id,street,state,city,zip_code,unit,country
0,1,549 Nguyen Underpass,NY,Ithaca,64986,Suite 698,USA
1,2,44362 Dennis Hill,CT,Waterbury,77673,,USA
2,3,9515 Joseph Manor,NY,Rochester,60151,Apt. 900,USA
3,4,273 Bernard Ports,NJ,Jersey City,40144,Apt. 062,USA
4,5,45976 Stone Squares,NY,Ithaca,25647,Apt. 678,USA
...,...,...,...,...,...,...,...
4799,2028,28291 Brandon Stravenue,NaN,Syracuse,74586,,USA
4800,2029,13328 Waters Ford,NaN,New York,97572,Suite 061,USA
4801,2030,033 Wilson Isle,NaN,Buffalo,16719,Suite 690,USA
4802,2031,7457 Paula Pines,NaN,New Haven,89681,,USA
4803,2032,92007 Michael Corner,NaN,New Haven,31827,Apt. 146,USA

In [272]:
# Drop duplicates
combined_addresses = combined_addresses.drop_duplicates()

#Insert the 'combined_addresses' into the sql's 'addresses' table
combined_addresses.to_sql(name='addresses', con=engine, if_exists='append', index=False)

32

In [273]:
# Drop duplicates
offices_df = offices_df.drop_duplicates()

#Insert the 'offices_df' into the sql's 'offices' table
offices_df.to_sql(name='offices', con=engine, if_exists='append', index=False)

804

In [274]:

employees_df

,employeeid,officeid,firstname,lastname,role,email,phonenumber,salary
0,1,1644,Brian,Klein,Manager,brian.klein@dreamhomes.nyc,535-856-7329,87173.68
1,2,2676,Ryan,Brown,Support,ryan.brown@dreamhomes.nyc,810-601-3316,82936.13
2,3,2156,Patrick,Coffey,Support,patrick.coffey@dreamhomes.nyc,564-198-2424,36539.21
3,4,1644,Samantha,Watson,Support,samantha.watson@dreamhomes.nyc,903-262-3479,80046.93
4,5,2336,Katherine,Howard,Support,katherine.howard@dreamhomes.nyc,352-399-5390,49379.10
...,...,...,...,...,...,...,...,...
115,116,1796,Gregory,White,Support,gregory.white@dreamhomes.nyc,470-528-9499,46576.68
116,117,2676,Christina,Evans,Agent,christina.evans@dreamhomes.nyc,869-632-9643,48283.19
117,118,2032,Joseph,Fry,Admin,joseph.fry@dreamhomes.nyc,582-461-1713,104445.89
118,119,2032,Pamela,Cruz,Support,pamela.cruz@dreamhomes.nyc,859-319-1720,113768.89
119,120,2032,Andrew,Hopkins,Manager,andrew.hopkins@dreamhomes.nyc,861-881-4227,81671.63

In [275]:
# Drop duplicates
employees_df = employees_df.drop_duplicates()

#Insert the 'employees_df' into the sql's 'employees' table
employees_df.to_sql(name='employees', con=engine, if_exists='append', index=False)

120

In [276]:

clients_df

,clientid,firstname,lastname,email,phonenumber,clienttype
0,1,Ashley,Melton,ashley.melton@example.com,6076274707,buyer
1,2,Melissa,Cooley,melissa.cooley@example.com,292-810-9738,buyer
2,3,Angela,Gibbs,angela.gibbs@example.com,001-766-553-7400,owner
3,4,Jasmine,Gardner,jasmine.gardner@example.com,535.355.1974x252,renter
4,5,Charles,Castro,charles.castro@example.com,511.384.1001x42377,owner
...,...,...,...,...,...,...
995,996,Martin,Horton,martin.horton@example.com,489-865-0219x64890,seller
996,997,David,Rich,david.rich@example.com,817-797-4913,buyer
997,998,Robert,Vega,robert.vega@example.com,(958)510-7518x6761,buyer
998,999,Maria,Jimenez,maria.jimenez@example.com,899-394-4893,seller
999,1000,Brandon,Miller,brandon.miller@example.com,+1-345-259-2125x79362,seller

In [277]:
# Drop duplicates
clients_df = clients_df.drop_duplicates()


#Insert the 'clients_df' into the sql's 'clients' table
clients_df.to_sql(name='clients', con=engine, if_exists='append', index=False)

1000

In [278]:
# Drop duplicates
home_listings_df = home_listings_df.drop_duplicates()

#Insert the 'home_listings_df' into the sql's 'home_listings' table
home_listings_df.to_sql(name='home_listings', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "home_listings" violates foreign key constraint "home_listings_addressid_fkey"
DETAIL:  Key (addressid)=(3619) is not present in table "addresses".

[SQL: INSERT INTO home_listings (homeid, addressid, sellerid, listingdate, price, status, bedroomcount, bathroomcount, squarefootage) VALUES (%(homeid)s, %(addressid)s, %(sellerid)s, %(listingdate)s, %(price)s, %(status)s, %(bedroomcount)s, %(bathroomcount)s, %(squarefootage)s)]
[parameters: ({'homeid': 8585561689, 'addressid': 1245, 'sellerid': 755, 'listingdate': datetime.datetime(2021, 5, 5, 0, 0), 'price': 4125, 'status': 'Rent', 'bedroomcount': 4, 'bathroomcount': 2, 'squarefootage': 2446}, {'homeid': 1550678141, 'addressid': 3619, 'sellerid': 951, 'listingdate': datetime.datetime(2022, 1, 24, 0, 0), 'price': 923862, 'status': 'Sale', 'bedroomcount': 3, 'bathroomcount': 2, 'squarefootage': 1853}, {'homeid': 8476052241, 'addressid': 5158, 'sellerid': 272, 'listingdate': datetime.datetime(2021, 7, 17, 0, 0), 'price': 4310, 'status': 'Rent', 'bedroomcount': 1, 'bathroomcount': 3, 'squarefootage': 3077}, {'homeid': 2107612233, 'addressid': 3604, 'sellerid': 357, 'listingdate': datetime.datetime(2023, 9, 10, 0, 0), 'price': 2664, 'status': 'Rent', 'bedroomcount': 3, 'bathroomcount': 2, 'squarefootage': 2079}, {'homeid': 4929040086, 'addressid': 8664, 'sellerid': 550, 'listingdate': datetime.datetime(2024, 2, 15, 0, 0), 'price': 781721, 'status': 'Sale', 'bedroomcount': 3, 'bathroomcount': 1, 'squarefootage': 1712}, {'homeid': 5607735460, 'addressid': 853, 'sellerid': 822, 'listingdate': datetime.datetime(2023, 7, 18, 0, 0), 'price': 843991, 'status': 'Sale', 'bedroomcount': 3, 'bathroomcount': 1, 'squarefootage': 843}, {'homeid': 1389717897, 'addressid': 7888, 'sellerid': 478, 'listingdate': datetime.datetime(2022, 8, 7, 0, 0), 'price': 859563, 'status': 'Sale', 'bedroomcount': 4, 'bathroomcount': 3, 'squarefootage': 2270}, {'homeid': 9388909297, 'addressid': 3879, 'sellerid': 433, 'listingdate': datetime.datetime(2023, 3, 7, 0, 0), 'price': 1615868, 'status': 'Sale', 'bedroomcount': 1, 'bathroomcount': 3, 'squarefootage': 1240}  ... displaying 10 of 1000 total bound parameter sets ...  {'homeid': 1858711056, 'addressid': 3664, 'sellerid': 145, 'listingdate': datetime.datetime(2023, 1, 11, 0, 0), 'price': 4081, 'status': 'Rent', 'bedroomcount': 3, 'bathroomcount': 2, 'squarefootage': 1167}, {'homeid': 1828375380, 'addressid': 3452, 'sellerid': 185, 'listingdate': datetime.datetime(2023, 4, 13, 0, 0), 'price': 2836, 'status': 'Rent', 'bedroomcount': 4, 'bathroomcount': 1, 'squarefootage': 553})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

In [244]:
# Create a set of valid addressid values from addresses_df
valid_addressids = set(combined_addresses['address_id'])

# Filter home_listings_df to only include rows with addressid that exists in valid_addressids
filtered_home_listings_df = home_listings_df[home_listings_df['addressid'].isin(valid_addressids)]

In [245]:
# Drop duplicates
filtered_home_listings_df = filtered_home_listings_df.drop_duplicates()

#Insert the 'filtered_home_listings_df' into the sql's 'home_listings' table
filtered_home_listings_df.to_sql(name='home_listings', con=engine, if_exists='append', index=False)

197

In [246]:
# Drop duplicates
amenities_df = amenities_df.drop_duplicates()

#Insert the 'amenities_df' into the sql's 'amenities' table
amenities_df.to_sql(name='amenities', con=engine, if_exists='append', index=False)

19

In [247]:
amenities_df

    amenityid      amenitytype
0           1             pool
1           2              gym
2           3          balcony
3           4          laundry
4           5          parking
5           6        fireplace
6           7          doorman
7           8            patio
8           9          storage
9          10           garden
10         11        roof deck
11         12        bike room
12         13         elevator
13         14     pet friendly
14         15   walk-in closet
15         16     washer/dryer
16         17      central air
17         18       dishwasher
18         19  hardwood floors

In [248]:
# Make a copy explicitly if it's a slice from another DataFrame
home_id_amenities_df = home_id_amenities_df.copy()
home_listings_df = home_listings_df.copy()
# Convert to string or the appropriate data type, ensuring both DataFrames match
home_id_amenities_df['homeid'] = home_id_amenities_df['homeid'].astype(str)
home_listings_df['homeid'] = home_listings_df['homeid'].astype(str)

# Validate types
print(home_id_amenities_df['homeid'].dtype)
print(home_listings_df['homeid'].dtype)

object
object

In [249]:
# Filter the DataFrame again
valid_homeids = set(filtered_home_listings_df['homeid'])
filtered_home_id_amenities_df = home_id_amenities_df[home_id_amenities_df['homeid'].isin(valid_homeids)]

In [250]:
filtered_home_id_amenities_df

       id      homeid  amenityid
0       1  8585561689          5
0       2  8585561689          8
0       3  8585561689          6
0       4  8585561689          7
0       5  8585561689          2
..    ...         ...        ...
977  3469  9770477885          5
984  3485  1429240846          2
984  3486  1429240846          1
985  3487  5569993693          5
985  3488  5569993693          6

[710 rows x 3 columns]

In [251]:
# Drop duplicates
filtered_home_id_amenities_df = filtered_home_id_amenities_df.drop_duplicates()

#Insert the 'filtered_home_id_amenities_df' into the sql's 'home_id_amenities' table
filtered_home_id_amenities_df.to_sql(name='home_id_amenities', con=engine, if_exists='append', index=False)

710

In [252]:
# Drop duplicates
neighborhood_features_df = neighborhood_features_df.drop_duplicates()

#Insert the 'neighborhood_features_df' into the sql's 'neighborhoodfeatures' table
neighborhood_features_df.to_sql(name='neighborhoodfeatures', con=engine, if_exists='append', index=False)

898

In [253]:
neighborhood_features_df

      featureid featuretype                     featurename
0             1      School     Jackson, Smith and Williams
1             2      School                      Wilson Inc
2             3      School          Brown, Martin and Mann
3             4      School                       Burns Inc
4             5      School                   Weaver-Vargas
...         ...         ...                             ...
1893       1894      School    Kelly, Joseph and Washington
1894       1895      School  Maldonado, Smith and Fernandez
1895       1896      School      Brown, Jackson and Hensley
1896       1897      School                      Smith-Good
1897       1898      School                   Rodriguez PLC

[1898 rows x 3 columns]

In [254]:
# Filter the DataFrame again
valid_homeids = set(filtered_home_listings_df['homeid'])
filtered_home_neighborhood_features_df = home_neighborhood_features_df[home_neighborhood_features_df['homeid'].isin(valid_homeids)]

In [255]:
home_neighborhood_features_df

Empty DataFrame
Columns: [id, homeid, featureid]
Index: []

In [256]:
filtered_home_neighborhood_features_df

Empty DataFrame
Columns: [id, homeid, featureid]
Index: []

In [260]:
# Drop duplicates
home_neighborhood_features_df = home_neighborhood_features_df.drop_duplicates()

#Insert the 'home_neighborhood_features_df' into the sql's 'home_neighborhood_features' table
home_neighborhood_features_df.to_sql(name='home_neighborhood_features', con=engine, if_exists='append', index=False)

0

In [258]:
past_transactions_df

,transactionid,homeid,buyerid,sellerid,employeeid,date,amount,transactiontype
1,2,8585561689,15.0,15.0,106,2021-06-09,4502.79,Sale
3,4,1550678141,787.0,787.0,86,2022-02-22,972329.33,Sale
7,8,2107612233,256.0,256.0,62,2023-09-26,2964.62,Sale
9,10,4929040086,145.0,145.0,103,2024-03-28,853213.22,Rent
11,12,5607735460,274.0,274.0,55,2023-09-05,955508.22,Rent
...,...,...,...,...,...,...,...,...
1977,1978,3858492578,522.0,522.0,108,2022-02-19,4869.51,Rent
1979,1980,7397953436,943.0,943.0,6,2021-05-31,2016269.60,Sale
1991,1992,7919467850,996.0,996.0,111,2022-07-06,1249915.20,Rent
1997,1998,1858711056,162.0,162.0,88,2023-02-15,4155.69,Rent
1999,2000,1828375380,860.0,860.0,60,2023-05-09,3096.90,Rent

In [259]:
# Filter the DataFrame again
valid_homeids = set(home_listings_df['homeid'])
filtered_past_transactions_df = past_transactions_df[past_transactions_df['homeid'].isin(valid_homeids)]

In [229]:
# Drop duplicates
filtered_past_transactions_df = filtered_past_transactions_df.drop_duplicates()

#Insert the 'filtered_past_transactions_df' into the sql's 'past_transactions' table
filtered_past_transactions_df.to_sql(name='past_transactions', con=engine, if_exists='append', index=False)

0

In [262]:
home_listings_df

,homeid,addressid,sellerid,listingdate,price,status,bedroomcount,bathroomcount,squarefootage
0,8585561689,1245,755,2021-05-05,4125,Rent,4,2,2446
1,1550678141,3619,951,2022-01-24,923862,Sale,3,2,1853
2,8476052241,5158,272,2021-07-17,4310,Rent,1,3,3077
3,2107612233,3604,357,2023-09-10,2664,Rent,3,2,2079
4,4929040086,8664,550,2024-02-15,781721,Sale,3,1,1712
...,...,...,...,...,...,...,...,...,...
995,7919467850,5705,543,2022-05-26,1231441,Sale,5,1,908
996,9775018591,6822,73,2021-12-20,3652,Rent,3,2,1019
997,6429659679,9762,561,2022-10-08,488191,Sale,1,2,2821
998,1858711056,3664,145,2023-01-11,4081,Rent,3,2,1167
999,1828375380,3452,185,2023-04-13,2836,Rent,4,1,553

In [263]:
value_to_check = 4251196064
is_value_in_column = home_listings_df['homeid'].isin([value_to_check]).any()
print(f"Is {value_to_check} in homeid? {is_value_in_column}")

Is 4251196064 in homeid? False

In [261]:
# Drop duplicates
property_maintenance_requests_df = property_maintenance_requests_df.drop_duplicates()

#Insert the 'property_maintenance_requests_df' into the sql's 'property_maintenance_requests' table
property_maintenance_requests_df.to_sql(name='property_maintenance_requests', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "property_maintenance_requests" violates foreign key constraint "property_maintenance_requests_homeid_fkey"
DETAIL:  Key (homeid)=(4251196064) is not present in table "home_listings".

[SQL: INSERT INTO property_maintenance_requests (maintenancerequestid, homeid, requestdate, issuedescription, urgencylevel, resolutionstatus) VALUES (%(maintenancerequestid)s, %(homeid)s, %(requestdate)s, %(issuedescription)s, %(urgencylevel)s, %(resolutionstatus)s)]
[parameters: ({'maintenancerequestid': 1, 'homeid': 4251196064, 'requestdate': datetime.date(2022, 1, 18), 'issuedescription': 'Onto green never young.', 'urgencylevel': 'Low', 'resolutionstatus': 'Completed'}, {'maintenancerequestid': 2, 'homeid': 2860731526, 'requestdate': datetime.date(2020, 10, 18), 'issuedescription': 'Side none dog mean series forward produce including.', 'urgencylevel': 'High', 'resolutionstatus': 'In Progress'}, {'maintenancerequestid': 3, 'homeid': 8737852610, 'requestdate': datetime.date(2020, 12, 20), 'issuedescription': 'Difficult term page economy.', 'urgencylevel': 'Medium', 'resolutionstatus': 'Completed'}, {'maintenancerequestid': 4, 'homeid': 6423898752, 'requestdate': datetime.date(2020, 9, 27), 'issuedescription': 'To seem store important.', 'urgencylevel': 'Low', 'resolutionstatus': 'Completed'}, {'maintenancerequestid': 5, 'homeid': 5908979080, 'requestdate': datetime.date(2022, 9, 14), 'issuedescription': 'Ok become author because environment foot lawyer.', 'urgencylevel': 'High', 'resolutionstatus': 'In Progress'}, {'maintenancerequestid': 6, 'homeid': 6772354521, 'requestdate': datetime.date(2023, 1, 29), 'issuedescription': 'Enough win ground adult significant great fly plant.', 'urgencylevel': 'Medium', 'resolutionstatus': 'Completed'}, {'maintenancerequestid': 7, 'homeid': 4898471763, 'requestdate': datetime.date(2023, 11, 30), 'issuedescription': 'Begin health final too any.', 'urgencylevel': 'Medium', 'resolutionstatus': 'In Progress'}, {'maintenancerequestid': 8, 'homeid': 2666210575, 'requestdate': datetime.date(2023, 7, 16), 'issuedescription': 'Record turn wind leg red especially management.', 'urgencylevel': 'High', 'resolutionstatus': 'Pending'}  ... displaying 10 of 150 total bound parameter sets ...  {'maintenancerequestid': 149, 'homeid': 5395966776, 'requestdate': datetime.date(2022, 11, 13), 'issuedescription': 'Service management add now suffer common.', 'urgencylevel': 'Medium', 'resolutionstatus': 'In Progress'}, {'maintenancerequestid': 150, 'homeid': 7628230772, 'requestdate': datetime.date(2021, 2, 25), 'issuedescription': 'Back civil fine her something amount.', 'urgencylevel': 'Low', 'resolutionstatus': 'Pending'})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

In [ ]:
#Drop duplicates
financial_records_df = financial_records_df.drop_duplicates()

#Insert the 'financial_records_df' into the sql's 'financial_records' table
financial_records_df.to_sql(name='financial_records', con=engine, if_exists='append', index=False)

In [288]:
#Drop duplicates
appointments_df = appointments_df.drop_duplicates()

#Insert the 'appointments_df' into the sql's 'appointments' table
appointments_df.to_sql(name='appointments', con=engine, if_exists='append', index=False)

600

In [287]:
#Drop duplicates
client_inquiries_df = client_inquiries_df.drop_duplicates()

#Insert the 'client_inquiries_df' into the sql's 'client_inquiries' table
client_inquiries_df.to_sql(name='client_inquiries', con=engine, if_exists='append', index=False)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "InquiryID" of relation "client_inquiries" does not exist
LINE 1: INSERT INTO client_inquiries ("InquiryID", clientid, date, i...
                                      ^

[SQL: INSERT INTO client_inquiries ("InquiryID", clientid, date, inquirytype, description) VALUES (%(InquiryID)s, %(clientid)s, %(date)s, %(inquirytype)s, %(description)s)]
[parameters: ({'InquiryID': 1, 'clientid': 996, 'date': datetime.date(2020, 2, 21), 'inquirytype': 'Investment', 'description': 'Think usually may recognize.'}, {'InquiryID': 2, 'clientid': 135, 'date': datetime.date(2021, 12, 23), 'inquirytype': 'Specific Home', 'description': 'News scene large good reality front.'}, {'InquiryID': 3, 'clientid': 842, 'date': datetime.date(2021, 5, 25), 'inquirytype': 'General', 'description': 'First listen hot range.'}, {'InquiryID': 4, 'clientid': 815, 'date': datetime.date(2021, 6, 6), 'inquirytype': 'Specific Home', 'description': 'Tell real must station we someone.'}, {'InquiryID': 5, 'clientid': 222, 'date': datetime.date(2021, 4, 11), 'inquirytype': 'Investment', 'description': 'Exist feel world police positive often remain group.'}, {'InquiryID': 6, 'clientid': 729, 'date': datetime.date(2021, 2, 14), 'inquirytype': 'Investment', 'description': 'Wait once present degree customer.'}, {'InquiryID': 7, 'clientid': 595, 'date': datetime.date(2022, 9, 19), 'inquirytype': 'Specific Home', 'description': 'Girl be night wait near them home return.'}, {'InquiryID': 8, 'clientid': 291, 'date': datetime.date(2021, 10, 16), 'inquirytype': 'Investment', 'description': 'Office also agreement would.'}  ... displaying 10 of 2000 total bound parameter sets ...  {'InquiryID': 1999, 'clientid': 311, 'date': datetime.date(2020, 2, 5), 'inquirytype': 'General', 'description': 'Beyond war religious occur center bad.'}, {'InquiryID': 2000, 'clientid': 792, 'date': datetime.date(2021, 9, 22), 'inquirytype': 'Investment', 'description': 'Accept event college.'})]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [286]:
#Drop duplicates
open_houses_df = open_houses_df.drop_duplicates()

#Insert the 'open_houses_df' into the sql's 'open_houses' table
open_houses_df.to_sql(name='open_houses', con=engine, if_exists='append', index=False)

DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

[SQL: INSERT INTO open_houses (openhouseid, homeid, date, starttime, endtime, notes) VALUES (%(openhouseid)s, %(homeid)s, %(date)s, %(starttime)s, %(endtime)s, %(notes)s)]
[parameters: ({'openhouseid': 1, 'homeid': 1421942427, 'date': datetime.datetime(2020, 7, 2, 7, 36, 2), 'starttime': '17:54:01', 'endtime': '23:54:01', 'notes': None}, {'openhouseid': 2, 'homeid': 4352473165, 'date': datetime.datetime(2022, 10, 17, 2, 54, 43), 'starttime': '13:16:24', 'endtime': '18:16:24', 'notes': None}, {'openhouseid': 3, 'homeid': 1508892460, 'date': datetime.datetime(2020, 2, 12, 9, 38, 10), 'starttime': '23:36:42', 'endtime': '03:36:42', 'notes': 'Money successful good significant style.'}, {'openhouseid': 4, 'homeid': 4578946712, 'date': datetime.datetime(2023, 10, 8, 18, 53, 5), 'starttime': '04:21:19', 'endtime': '10:21:19', 'notes': 'Son particularly participant culture huge attorney.'}, {'openhouseid': 5, 'homeid': 9850153889, 'date': datetime.datetime(2023, 5, 20, 3, 17, 12), 'starttime': '08:34:53', 'endtime': '12:34:53', 'notes': None}, {'openhouseid': 6, 'homeid': 3330500566, 'date': datetime.datetime(2021, 6, 13, 6, 3, 27), 'starttime': '07:41:54', 'endtime': '10:41:54', 'notes': 'Less better school onto economy.'}, {'openhouseid': 7, 'homeid': 4677453554, 'date': datetime.datetime(2022, 4, 23, 21, 16, 20), 'starttime': '08:25:33', 'endtime': '10:25:33', 'notes': None}, {'openhouseid': 8, 'homeid': 5371432554, 'date': datetime.datetime(2022, 7, 7, 17, 38, 35), 'starttime': '00:22:13', 'endtime': '06:22:13', 'notes': 'Push every after west.'}  ... displaying 10 of 80 total bound parameter sets ...  {'openhouseid': 79, 'homeid': 8471862726, 'date': datetime.datetime(2022, 2, 11, 4, 48, 45), 'starttime': '07:33:27', 'endtime': '11:33:27', 'notes': 'Woman family write project shoulder.'}, {'openhouseid': 80, 'homeid': 7314189443, 'date': datetime.datetime(2022, 12, 12, 16, 35, 17), 'starttime': '08:42:46', 'endtime': '14:42:46', 'notes': 'Administration his economy age chance community class.'})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

In [285]:
#Drop duplicates
user_favorites_df = user_favorites_df.drop_duplicates()

#Insert the 'user_favorites_df' into the sql's 'user_favorites' table
user_favorites_df.to_sql(name='user_favorites', con=engine, if_exists='append', index=False)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "FavoritedOnDate" of relation "user_favorites" does not exist
LINE 1: INSERT INTO user_favorites (userid, homeid, "FavoritedOnDate...
                                                    ^

[SQL: INSERT INTO user_favorites (userid, homeid, "FavoritedOnDate") VALUES (%(userid)s, %(homeid)s, %(FavoritedOnDate)s)]
[parameters: ({'userid': 552, 'homeid': 9579006329, 'FavoritedOnDate': datetime.datetime(2020, 7, 14, 9, 6, 25)}, {'userid': 678, 'homeid': 2970238604, 'FavoritedOnDate': datetime.datetime(2022, 12, 4, 22, 38, 7)}, {'userid': 818, 'homeid': 6294540070, 'FavoritedOnDate': datetime.datetime(2022, 7, 1, 19, 36, 50)}, {'userid': 176, 'homeid': 4441804088, 'FavoritedOnDate': datetime.datetime(2022, 9, 7, 11, 18, 47)}, {'userid': 733, 'homeid': 5511678597, 'FavoritedOnDate': datetime.datetime(2020, 12, 14, 14, 12, 29)}, {'userid': 208, 'homeid': 5808216163, 'FavoritedOnDate': datetime.datetime(2021, 9, 8, 14, 7, 30)}, {'userid': 986, 'homeid': 2071853376, 'FavoritedOnDate': datetime.datetime(2021, 8, 2, 8, 45, 21)}, {'userid': 921, 'homeid': 7973263918, 'FavoritedOnDate': datetime.datetime(2021, 10, 18, 13, 58, 25)}  ... displaying 10 of 300 total bound parameter sets ...  {'userid': 131, 'homeid': 1087279822, 'FavoritedOnDate': datetime.datetime(2022, 4, 17, 4, 13, 37)}, {'userid': 391, 'homeid': 8584942181, 'FavoritedOnDate': datetime.datetime(2020, 5, 10, 16, 44, 37)})]
(Background on this error at: https://sqlalche.me/e/14/f405)